### PR TITLE
WIP: added documentation for circe-derivation

### LINKED ISSUE #188: add documentaion
documentation covering edge cases, default behaviours and limitations would be nice.

would prefer adding it to main [circe docs](https://circe.github.io/circe/) than a separate microsite. 
if no objections, i can start making a PR for it.

### PR DESCRIPTION
**Pull request by shrynx**
adds documentation for [circe-derivation](https://github.com/circe/circe-derivation)

closes https://github.com/circe/circe-derivation/issues/188

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks! The content looks good to me. The CI failure is because we'll need to add circe-derivation to the docs build (since they're compiled). I can look at that this weekend, unless you want to take a shot at it sooner.

**Comment by shrynx** [comment]
yes i am waiting for the new release of `circe-derivation` to link to as old will give errors
will update this once after release

**Comment by travisbrown** [comment]
@shrynx Ah, got it, makes sense. I'll try to get around to publishing an M4 today.

**Comment by shrynx** [comment]
@travisbrown i added `circe-derivation` to deps but not sure why is one failing

**Comment by travisbrown** [comment]
@shrynx It says the build was stalled, so probably just Travis CI being Travis CI. I restarted the job.

**Comment by shrynx** [comment]
@travisbrown looks like it is getting stuck only on scala 2.12.10

**Comment by hamnis** [comment]
Closed due to age.

Please notify maintainers if this is done in error.

**Pull request closed without merging**
