### PR TITLE
Add fs2 module

### PR DESCRIPTION
**Pull request by n4to4**
#484

Tried to port the iteratee.io version and it seems to be working.
Cross compiling for 2.10.x is failing because fs2 doesn't support 2.10.x ?.
And I couldn't find a way to fix it (maybe sbt-doge?), so just left it for now.

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks—I'll review in detail tomorrow.

I was really, really happy to be able to get rid of sbt-doge last month, and I'm not excited about bringing it back, but I guess we'll have to.

**Comment by n4to4** [comment]
@travisbrown what's the status? should I have to do something (sbt-doge settings)? I will close this if it's not useful.

**Comment by travisbrown** [comment]
No, it's definitely useful, @n4to4, but we will either need to reinstate sbt-doge or make this a separate circe organization repository. I don't have a strong preference, but I think it fits better here, even if it means we have to go back to sbt-doge.

**Comment by travisbrown** [comment]
@n4to4 I'd like to go ahead and publish a circe 0.8.0 release in the next few days, and I definitely want to include this. Would you have time to handle the doge-ification? If not I should be able to get to it this weekend. /cc @fommil

**Comment by n4to4** [comment]
@travisbrown I'll give it a try

**Comment by fommil** [comment]
the one thing I'd say about this impl is that it can be a bit of a pain to have to supply the type params (often the compiler fails to infer the types), can you think of a way that this could be simplified? (not the end of the world if not), e.g. in `fs2-http`

```scala
    clientTask.flatMap { client =>
      client.request(backlogRequest).flatMap { resp =>
        resp.body.chunks.through(byteParser).through(decoder[Task, Backlog])
      }.runLast.map(_.get)
    }
```

it would be nice to be able to just say `decoder` or `decoder[Backlog]` instead of having to mention the effect. But at least there are no other type params, so maybe I'm just being pedantic.

**Comment by travisbrown** [comment]
@n4to4 I think I've decided to do this as a new repo, if that's okay with you. I've `filter-branch`-ed your commits and added the build stuff [here](https://github.com/circe/circe-fs2).

**Comment by n4to4** [comment]
@travisbrown No problem at all 👍

**Comment by travisbrown** [comment]
Okay, closing since this is live at [circe/circe-fs2](https://github.com/circe/circe-fs2).

**Pull request closed without merging**
