### PR TITLE
Organization Github Pages

### PR DESCRIPTION
**Pull request by joan38**
Hi,

We currently have a microsite on a project Github Page at https://circe.github.io/circe/.
This is a proposal to move this site on a organization Github Page at https://circe.github.io.
We could then setup the https://circe.io as a [Custom domain](https://help.github.com/articles/using-a-custom-domain-with-github-pages/) to this site.

This PR also requires to:
- [ ] Create the repository `circe/circe.github.io`
- [ ] Initialize an untracked and empty master branch on `circe/circe.github.io`:
  ```
  git checkout --orphan gh-pages
  git commit --allow-empty -m "Initialize master branch"
  git push origin master
  ```
- [ ] Publish the new site:
  ```
  sbt publishMicrosite
  ```
- [ ] Set up the custom domain `circe.io`:
  https://help.github.com/articles/quick-start-setting-up-a-custom-domain/
- [ ] Put a redirect on the current project site so that the current redirects to the new URI:
  ```
  <meta http-equiv="refresh" content="0; URL='http://circe.io'" />
  ```

See example with https://github.com/OrkestraCD and https://orkestra.tech or https://orkestracd.github.io.

Thanks

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks for kicking this off, @joan38—I agree it's something we should do. Will aim to follow up in the next week or two.

**Comment by joan38** [comment]
Thanks @travisbrown, I can assist on any of the steps since I just set it up for https://orkestra.tech
Let me know when you have time in the following weeks.

**Comment by joan38** [comment]
Hi, any spare time to spend in this?

**Comment by hamnis** [comment]
Closed due to age.

Please notify maintainers if this is done in error.

**Pull request closed without merging**
