### PR TITLE
Update Cats to 1.5.0, Scala 2.13 to 2.13.0-M5

### PR DESCRIPTION
**Pull request by travisbrown**
I'll publish this as 0.11.0-M1 tomorrow if everything looks alright.

### CODE REVIEW

**Comment by SethTisue** [comment]
anything I or other contributors can do to help this move forward?

**Comment by SethTisue** [comment]
looks like the M5 build is stuck on

```
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.spire-math:jawn-parser_2.13.0-M5:0.13.0:
[error]         not found:
[error]             /home/travis/.ivy2/local/org.spire-math/jawn-parser_2.13.0-M5/0.13.0/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.13.0-M5/0.13.0/jawn-parser_2.13.0-M5-0.13.0.pom
[error]             https://oss.sonatype.org/content/repositories/releases/org/spire-math/jawn-parser_2.13.0-M5/0.13.0/jawn-parser_2.13.0-M5-0.13.0.pom
[error]             https://oss.sonatype.org/content/repositories/snapshots/org/spire-math/jawn-parser_2.13.0-M5/0.13.0/jawn-parser_2.13.0-M5-0.13.0.pom
```

I opened https://github.com/non/jawn/issues/120 on it

**Comment by travisbrown** [comment]
@SethTisue Yeah, Jawn is the only thing we're waiting on. I've tried pinging @non a number of times over the past couple of months, but haven't heard anything, so I'll probably just fork it once Cats 1.5.0 is ready.

**Comment by SethTisue** [comment]
perhaps someone watching this repo could submit an M4->M5 upgrade over at https://github.com/non/jawn so that all Erik would need to do is pull publishing levers. M4->M5 is usually an easy bump to do

**Comment by travisbrown** [comment]
@SethTisue We've had a PR open for a couple of months with no response: https://github.com/non/jawn/pull/117

**Pull request merged**
