### PR TITLE
Cross-build jawn module for Scala.js

### PR DESCRIPTION
**Pull request by armanbilge**
As discussed in https://github.com/typelevel/jawn/pull/351. This was very straightforward to execute.

Thanks in advance!

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, looks reasonable to me. I'll probably publish an 0.15.0-M1 this weekend that will include this.

**Comment by armanbilge** [comment]
Thank you very much for the prompt review! Yes please, a milestone release would be _very_ helpful indeed 😄

**Comment by armanbilge** [comment]
@travisbrown I'd still really love a (snapshot) release of this please! If you have a chance.

Once it's released, I'm happy to follow-up with a PR at https://github.com/circe/circe-fs2/.

**Comment by travisbrown** [comment]
@armanbilge Sorry about the delay. 0.15.0-M1 is on its way to Maven Central now. I'll try to put together the release notes, etc. later today.

**Comment by armanbilge** [comment]
No problem!! Thank you very much, this is a big win for https://github.com/http4s/http4s/pull/4938.

**Pull request merged**
