### PR TITLE
Do not differentiate between native and non-native for refined

### PR DESCRIPTION
**Pull request by hamnis**
Use 0.11.1 for both

### CODE REVIEW

**Comment by zarthross** [comment]
@hamnis Is this not a binary breaking change for users of circe-refined?  

The reason native use a newer version was because native required a newer version and did not exist when circe-refined was created, so in a way wasn't binary breaking.

**Comment by hamnis** [comment]
it might be, but do we have to be so strict with regards to binary breakage in a third party integration module?

If we are, we should spin it off into an own repo, which has its own release schedule.

**Comment by armanbilge** [comment]
> If we are, we should spin it off into an own repo, which has its own release schedule.

Agree. We should do this for all the circe integrations, same as we did for http4s.

**Comment by hamnis** [comment]
Closing for now. We will spin off refined into a separate repo

**Pull request closed without merging**
