### PR TITLE
Use scala-java-time for circe-java8 on Scala.js

### PR DESCRIPTION
**Pull request by liff**
Right now this doesn't work too well yet due to cquiroz/scala-java-time#9 and `LocalDateTime.format` hitting scala-js/scala-js#2755.

Perhaps one day in not too distant future, though :)

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, @liff! Do you think this is worth including in the next release even with those issues?

**Comment by liff** [comment]
The Scala.js bug breaks encoding (IIRC) of everything except for `Instant` and `LocalDate`, so probably best to wait for 0.6.15.

**Comment by liff** [comment]
This now looks like it's working fine with scala-java-time 2.0.0-M9 and Scala.js 0.6.15.

**Comment by dpnova** [comment]
If anyone stumbles on this issue I worked around it like this:

1. Add the scalajs-java-time dep: `"org.scala-js" %%% "scalajs-java-time" % "0.2.0"`
2. Manually create encoders/decoders:

```
    val formatterISO = DateTimeFormatter.ISO_DATE
    implicit val encodeDate: Encoder[ZonedDateTime] = Encoder.encodeString.contramap[ZonedDateTime](formatterISO.format(_))

    implicit val decodeDate: Decoder[ZonedDateTime] = Decoder.decodeString.emap {
      str => Either.catchNonFatal(ZonedDateTime.parse(str, formatterISO)).leftMap(t => "ZonedDateTime")
    }
```

**Comment by travisbrown** [comment]
@liff @dpnova So this is ready to merge (with scala-java-time for now, at least until scalajs-java-time gets `DateTimeFormatter`, etc.)? I just rebased and ran the tests locally and it looks fine.

**Comment by dpnova** [comment]
Yep scala-java-time worked for my workaround, assuming this will work fine
too. I'll pull and run the tests when I get to work this morning.

**Comment by travisbrown** [comment]
Cool, thanks @liff, @dpnova.

**Pull request merged**
