### PR TITLE
Only set scalaJSLinkerConfig for Scala.js projects (#1679)

### LINKED ISSUE #1679: Fix warnings on sbt launch
For a while the build has given a screenful of errors when you start an sbt console:
```scala
[warn] there are 21 keys that are not used by any other settings/tasks:
[warn]  
[warn] * benchmark / Test / scalaJSLinkerConfig
[warn]   +- /home/travis/projects/scala/circe/build.sbt:121
[warn] * benchmarkDotty / Test / scalaJSLinkerConfig
[warn]   +- /home/travis/projects/scala/circe/build.sbt:121
...
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
```
I haven't investigated these and barely even notice them now, but we should try to get rid of them. My guess is searching for the warning messages should lead to a fix, I just haven't got around to doing this.

### PR DESCRIPTION
**Pull request by aumann**
Fixes #1679 

The warnings have been triggered for all JVM projects. This PR moves the linker setting to only be applied to JS projects.

This was straightforward for all circeCrossModules.

For the two "scalaJs only" projects I have added the setting manually.

Is there a way how I can test whether the setting is indeed still applied to all JS projects?

### CODE REVIEW

**Comment by aumann** [comment]
Hmm, is there any feedback on this? If there are problems with the approach in general, I'm happy to try something different.

**Comment by travisbrown** [comment]
No, I'm sorry, it's my fault—I just missed this. I was taking a look today because I was publishing a new milestone. Do you mind resolving the conflict (which looks small)? I can also do it.

**Comment by aumann** [comment]
> No, I'm sorry, it's my fault—I just missed this. I was taking a look today because I was publishing a new milestone. Do you mind resolving the conflict (which looks small)? I can also do it.

No harm done - I'll resolve the conflict

**Comment by aumann** [comment]
Rebased, conflicts resolved.

Let me know if I should also take a look at fixing the "blaSetting in Compile" vs "Compile / blaSetting" warnings with sbt 1.5 in a separate pull request (probably after you are through with your release routine to avoid conflicts).

**Comment by travisbrown** [comment]
Looks good to me, and yes, if you can take a look at the new warnings that'd be great, thanks.

**Pull request merged**
