### PR TITLE
Add workarounds for knownDirectSubclasses compile error

### PR DESCRIPTION
**Pull request by lloydmeta**
@travisbrown [mentioned](https://github.com/circe/circe/issues/639#issuecomment-303118282) that he would like to see some detailed docs that specifically dealt with the dreaded `knownDirectSubclasses` issue added so this is my attempt at it.

### CODE REVIEW

**Comment by travisbrown** [comment]
This is awesome, thanks @lloydmeta.

**Comment by ngbinh** [comment]
just a comment: we are using `semiauto` and the problem still persists (probably less frequently)

**Comment by szoio** [comment]
As a relatively simple alternative when none of the above works:
Move the sealed trait case class definitions into a different module from the one that contains your generic auto derivation. 
That was the only way I was able to get around this one.

**Comment by nikitapecasa** [comment]
@szoio Hi, thanks for your comment, it solved my problem.

I think this workaround should be added to docs.

@travisbrown What do you think?

**Comment by travisbrown** [comment]
@nikitapecasa Sounds reasonable to me! (if it's not there already?).

**Comment by szoio** [comment]
@nikitapecasa happy it worked for you.

**Comment by PhilAndrew** [comment]
I'm getting this error and I don't really understand what I'm supposed to do.

**Pull request merged**
