### PR TITLE
Added custom key string in generic extra

### PR DESCRIPTION
**Pull request by aparo**
During the wrapping external API and general in real world there are a lot of key values in JSOn that must be contains custom values such as "@timestamp", "my-wonderful-field" and so on.
This pull request add an annotation *Key* that allows to define a string that will be used in de/serialize an objects.
For example
```
case class ConfigExampleFoo(thisIsAField: String, a: Int = 0, @Key("myField") b: Double)
```

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, @aparo! I'll review this weekend.

**Comment by aparo** [comment]
I saw that it requires that case class Key needs to extend Annotation.
For the second error, I don't know probably it's fired by the first one.

**Comment by aparo** [comment]
Travis, I run the full test suite on my branch without problems. Now I see codecov issues in files that I never changed.
This feature is very common in business applications.

**Comment by travisbrown** [comment]
Ugh, this totally slipped off my radar. I'm at NE Scala today and tomorrow but should be able to get this done this weekend.

**Comment by aparo** [comment]
Don't worry. I fixed the scalacheck errors. I'll add some docs examples.

From ConfiguredJsonCodecWithKeySuite:

```scala
@ConfiguredJsonCodec
sealed trait ConfigExampleBase
case class ConfigExampleFoo(thisIsAField: String, a: Int = 0, @Key("myField") b: Double) extends ConfigExampleBase

  "ConfiguredJsonCodec" should "support key annotation and configuration" in forAll { (f: String, b: Double) =>
    val foo: ConfigExampleBase = ConfigExampleFoo(f, 0, b)
    val json = json"""{ "type": "ConfigExampleFoo", "this_is_a_field": $f, "myField": $b}"""
    val expected = json"""{ "type": "ConfigExampleFoo", "this_is_a_field": $f, "a": 0, "myField": $b}"""

    assert(Encoder[ConfigExampleBase].apply(foo) === expected)
    assert(Decoder[ConfigExampleBase].decodeJson(json) === Right(foo))
  }
```

**Comment by aparo** [comment]
Do you have any news about this pulll request?
Do you need something else that I can figure out?

**Comment by travisbrown** [comment]
Okay, this has languished a long, long time, but I want it in 0.8.0 and I've got a few little changes that I think should go in (e.g. deriving the labelling from `LabelledGeneric` instead of `DefaultSymbolicLabelling` so that people who provide their own `LabelledGeneric` don't get inconsistent results, etc.). I'll be opening a PR against your branch shortly, @aparo.

**Comment by travisbrown** [comment]
Included in #616.

**Pull request closed without merging**
