### PR TITLE
Remove benchmarks of 3rd party libraries

### PR DESCRIPTION
**Pull request by jensraaby**
See #525.

This removes the benchmarks against 3rd party JSON libraries from the main repository.

### CODE REVIEW

**Comment by jensraaby** [comment]
@travisbrown if you prefer, I can keep the benchmarks of Circe itself in the repo and do this as a simple 'remove 3rd party benchmarks' PR?

**Comment by travisbrown** [comment]
@jensraaby Yeah, right now I think `CirceDerivationBenchmark` is the only one that needs to stay, but we definitely want to keep it around in this repo (and will probably add other internal benchmarks in the future).

**Comment by jensraaby** [comment]
I've restored the `CirceDerivationBenchmark` benchmark and just removed the 3rd party comparisons. Obviously I need to remove the other commit - just let me know if its OK to rebase.

**Comment by travisbrown** [comment]
:+1:, looks good to me.

**Comment by n4to4** [comment]
We should probably update 'docs' (eg. referece to the Benchmark.scala) in this PR or another.

**Comment by travisbrown** [comment]
Sorry, @jensraaby—one last thing. Do you mind reinstating the deleted tests for the derivation suite?

@n4to4 We'll also need to add a reference in the list of circe org projects in the README, but I'm happy to have the doc updates happen in a follow-up PR.

**Comment by jensraaby** [comment]
@travisbrown I've hopefully covered everything now, including updating the link in the microsite documentation. Also removed the 2.12 branching logic in .travis.yml, as that was caused by the removed dependencies.

**Comment by travisbrown** [comment]
Great, thanks again, @jensraaby!

**Pull request merged**
