### PR TITLE
Link directly to `io.circe` package in API documentation

### PR DESCRIPTION
**Pull request by x3ro**
This is, in my opinion, a small UX improvement over linking to the
root package, as it saves a couple of clicks that one always needs
to make when using the `Documentation` link on the microsite.

In addition I took the liberty of changing "Documentation" to
"API documentation" in order to make clearer what's being linked to
(this was inspired by the [Cats documentation](https://typelevel.org/cats/))

This is the API documentation start package after the change:

Screenshot 2020-10-17 at 01 14 26

### CODE REVIEW

**Comment by x3ro** [comment]
I'm not entirely sure why this build fails, can you help me out 🤔

**Comment by travisbrown** [comment]
This looks reasonable to me, thanks! I think running `sbt scalafmt` should fix the CI failure.

**Comment by x3ro** [comment]
Mmh, unfortunately it still complains about lines in the `packages.scala` comment being too long. There doesn't seem to be a way to make them shorter than 120 characters though, or at least not without e.g. link shorteners which doesn't seem like a good idea :D Any ideas?

**Comment by travisbrown** [comment]
Hmm, I think changing the Scalafmt config to accommodate the longer comment is the best choice, then.

**Comment by x3ro** [comment]
I didn't find a way to disable this limitation for comments specifically, at least not [here](http://www.scalastyle.org/rules-1.0.0.html) so I just disabled it locally for the comment.

**Comment by x3ro** [comment]
The build is passing now :) What do you think, can this be merged or is more work needed?

**Comment by travisbrown** [comment]
Merging now, thanks again. Will try to get around to publishing this weekend.

**Comment by x3ro** [comment]
Thanks :) I'll potentially have time to submit another 1 or 2 PRs that touch the docs this weekend, so (in case they get accepted) maybe they can be published all in one go 🎉

**Pull request merged**
