### PR TITLE
Use Coursier

### PR DESCRIPTION
**Pull request by backuitist**

### CODE REVIEW

**Comment by backuitist** [comment]
Closing/reopening to re-run the build. I've cached the .coursier directory on travis, and I'd like to see if that improves build time.

**Comment by alexarchambault** [comment]
@backuitist If you want sbt-coursier to fetch the (other) sbt plugins too, you can add it to `project/project/plugins.sbt` (like [here](https://github.com/coursier/coursier/blob/master/project/project/plugins.sbt)).

**Comment by backuitist** [comment]
@alexarchambault good idea! I've added it.

**Comment by travisbrown** [comment]
Thanks @backuitist, @alexarchambault!

**Pull request merged**
