### PR TITLE
Fix 2104: Proxy remaining Codec methods

### PR DESCRIPTION
**Pull request by solarized-fox**
a fix wrt to #2104, I believe these are all the nonfinal methods that needed rerouting. I ran `test` and `scalastyle` in sbt, and it should be good to go

### CODE REVIEW

**Comment by zarthross** [comment]
@solarized-fox Mind creating a unit test so we can prevent future regressions?

**Comment by drewfeelsblue** [comment]
the same for `AsObject.from`
```
  val decoder = Decoder.decodeOption[Int]
  val codec   = Codec.AsObject.from[Option[Int]](decoder, null)
  val hCursor = Json.obj().hcursor

  decoder.at("x").tryDecode(hCursor) // Right(None)
  codec.at("x").tryDecode(hCursor)   // Left(DecodingFailure at .x: Missing required field)
```

`AsArray.from`?

**Comment by solarized-fox** [comment]
> @solarized-fox Mind creating a unit test so we can prevent future regressions?

you mean a test to make sure `Codec.from(…).method(…) == coder.method(…)`, or a test to make sure all nonfinal methods are delegated? either way I should be able to do that, might take a hot minute though

**Comment by solarized-fox** [comment]
all right, is this satisfactory as a test?

**Review by zarthross — APPROVED** [review]

**Review by zmccoy — APPROVED** [review]

**Pull request merged**
