### PR TITLE
Added `Json.dropNullValues`.

### PR DESCRIPTION
**Pull request by orium**

### CODE REVIEW

**Comment by orium** [comment]
Not sure if this is "too specific" to be added to `Json`, but it is something that I often use and can be useful for others (see #584 and #585).

Maybe it would be nicer to make it `def dropNullValues(deep: Boolean = false): Json`?

**Comment by poslegm** [comment]
It seems very useful for me! Any chance that it will be merged?

**Comment by travisbrown** [comment]
I've been wanting to avoid this and leave the presence or absence of null values as a printing-level issue, but there seems to be enough demand that I guess I should give that up. I'll merge this as-is, and if someone wants to add the deep version we can review it when it comes up.

**Comment by realvictorprm** [comment]
funny thing, this is just something I wanted to use and then I noticed that this was merged a day ago :smile: nice stuff :smiley:

**Pull request merged**
