### PR TITLE
Adding ensure method

### PR DESCRIPTION
**Pull request by saint1991**
This PR adds `ensure` method to the `Decoder`.
The motivation here is to provide composable error checking mechanism in both fail-fast and accumulating mode as discussed in #907.

A usage example is below.

```
  import io.circe.generic.semiauto._
  import io.circe.parser._

  case class Foo(a: String, b: List[String])

  implicit val decoder = deriveDecoder[Foo]
    .ensure(_.a.nonEmpty, "a should not be empty")
    .ensure(_.b.nonEmpty, "b should not be an empty list")


  val json =
    """{
      |  "a": "",
      |  "b": []
      |}
    """.stripMargin

  // Left(DecodingFailure(a should not be empty, List()))
  decode(json)

  // Invalid(NonEmptyList(DecodingFailure(a should not be empty, List()), DecodingFailure(b should not be an empty list, List())))
  decodeAccumulating(json) 
```

BTW, I felt that `validation` method has a bit inconsistent semantics because it is neither fail-fast nor accumulating. The final validation call overwrites all other calls. 
Is it the intended behaviour?

If so, its signature is misleading...
It's only my feeling but returning Decoder implies it is composable by method chain like the above example.

### CODE REVIEW

**Comment by saint1991** [comment]
I'm going to add tests against `ensure` after the discussion

**Comment by travisbrown** [comment]
Thanks @saint1991! Will get feedback posted asap.

**Comment by saint1991** [comment]
Sorry I misunderstood, `Decoder` is a type class, so available choices for returning type of `validate` are only `Decoder` or `Unit`.
The former is a bit misleading as discussed in #907 but another one is not functional...

**Comment by travisbrown** [comment]
Hi @saint1991! Sorry for the long delay, but I think this would be a good addition for 0.10.0. If you happen to have tests around I'd definitely appreciate a follow-up PR, but otherwise I can add some later today.

**Comment by saint1991** [comment]
@travisbrown No problem. Thank you for merging this!
I'll add tests for this in a following PR.

**Pull request merged**
