### PR TITLE
Scala Native

### PR DESCRIPTION
**Pull request by armanbilge**
Closes https://github.com/circe/circe/pull/1929. See also https://github.com/circe/circe/issues/1077.

### CODE REVIEW

**Comment by armanbilge** [comment]
@zarthross @zmccoy polite ping, I know you are almost definitely underwater 😅 it would be truly excellent to get this into a published released as soon as possible: it will unblock an entire Scala Native ecosystem built on Circe—which is no small thing.

Now that the build is using sbt-typelevel, I'm happy to setup CI release for you so it can be a one-click publish job :)

There are no source code changes in this PR :) it's 100% build-hacking, for better or for worse.

Bonus: here's an example app demoing Circe Native with and Http4s Native cURL backend!
https://github.com/http4s/http4s-curl/blob/f29afa262757936b8f16837d46b6e357284d1b80/example/src/main/scala/ExampleApp.scala

**Comment by zmccoy** [comment]
Hi @armanbilge, @zarthross  and I will try to get to this early next week if that's alright.  This weekend / Monday is a holiday and I'm away from the computer.

**Comment by armanbilge** [comment]
Have a great weekend! I should try to follow suite 😆

**Review by zarthross — DISMISSED** [review]

**Comment by zarthross** [comment]
@armanbilge Could this PR be made against series/0.14 branch in a bin-compat way?  We'd probably want to release an 0.14 scala-native release if possible.

**Comment by armanbilge** [comment]
Yes, absolutely. We definitely want this in an 0.14 release. I didn't change any sources so there should be no bincompat issues.

**Comment by armanbilge** [comment]
Test failure is not specific to Scala Native, I was able to replicate it on the JVM. I believe @isomarcte recently revised this suite? 

```
==> X io.circe.pointer.literal.PointerInterpolatorSuite.The pointer string interpolater should work with arbitrary interpolated strings  0.246s munit.FailException: /workspace/circe/modules/pointer-literal/src/test/scala/io/circe/pointer/literal/PointerInterpolatorSuite.scala:49
48:
49:  property("The pointer string interpolater should work with arbitrary interpolated strings") {
50:    Prop.forAll(ScalaCheckInstances.genPointerReferenceString) { (v: String) =>

Failing seed: qzbVz6jmqdOrJ6jdDd_E9p990OQHEWa1EeruSk3VXuF=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "qzbVz6jmqdOrJ6jdDd_E9p990OQHEWa1EeruSk3VXuF="

Falsified after 72 passed tests.
> Labels of failing property: 
Expected Right(/foo/~0/bar) but got Left(io.circe.pointer.PointerSyntaxError: Syntax error at 5; expected: token character)
> ARG_0: "~"
> ARG_0_ORIGINAL: "뙪쀿냡㙼㴗Ꝙ阎⿖鶕埝覃廦羄剘竀⅁迠䵿異謋⥿튏╰厳셖ᬵ┺翌话ˑ쇴椅鳟튯캧饞朗㢗濓ደ盷봙醛莪ﵴ넼孅瘭ޢ깬ཪ㑹쐉鉚鶷삀葬ퟌ讛狾噙~1䒤訢薸쇝ᄇ톧펥"
```

**Comment by armanbilge** [comment]
This time a JVM failure ...
```
==> X io.circe.pointer.literal.PointerInterpolatorSuite.The pointer string interpolater should work with arbitrary interpolated strings  0.427s munit.FailException: /home/runner/work/circe/circe/modules/pointer-literal/src/test/scala/io/circe/pointer/literal/PointerInterpolatorSuite.scala:47
46:
47:  property("The pointer string interpolater should work with arbitrary interpolated strings") {
48:    Prop.forAll(ScalaCheckInstances.genPointerReferenceString) { (v: String) =>

Failing seed: dEYU1agSRFmo29QBq3dMD5Z7J7h7UDHzuNpeGVbviQO=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "dEYU1agSRFmo29QBq3dMD5Z7J7h7UDHzuNpeGVbviQO="
```

**Review by zarthross — APPROVED** [review]

**Comment by adampauls** [comment]
Amazing, thanks! Just a minor nit: you pointed to my WIP PR and not the underlying issue. Probably best to say that this PR supersedes that PR instead of "closing" it, or say "close" and point to the underlying issue (or both).

**Comment by armanbilge** [comment]
> Probably best to say that this PR supersedes that PR instead of "closing" it, or say "close" and point to the underlying issue (or both).

This was intentional. GitHub doesn't recognize the term "supersedes" last I checked, but it does recognize "close" to automatically close your PR when this one merges. although it seems that Darren already closed it :)

I'll update to point to the original issue, but that one is rather old and already closed as well!

**Comment by isomarcte** [comment]
> Test failure is not specific to Scala Native, I was able to replicate it on the JVM. I believe @isomarcte recently revised this suite?

I was sure I fixed that...

**Comment by armanbilge** [comment]
On the 0.14.x branch? I'm afraid I've lost track between the 0.14, 0.15, and main branches.

**Comment by isomarcte** [comment]
It might only be on 0.15.

**Review by zmccoy — APPROVED** [review]

**Comment by zarthross** [comment]
> On the 0.14.x branch? I'm afraid I've lost track between the 0.14, 0.15, and main branches.

@armanbilge `series/0.14.x` is now the default branch, `main` is no more, and `series/0.15.x` is the home of new stuff no compatible with series/0.14.  Hopefully this helps.

**Comment by armanbilge** [comment]
Thanks, that helps clarify things! Let me know if I can help with a new 0.14.x release :)

**Comment by plokhotnyuk** [comment]
Thank you, Everyone!

Just released [a new version of the circe booster with Scala Native support](https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v2.17.4).

**Pull request merged**
