### PR TITLE
Add Encoder.at

### LINKED ISSUE #1536: Encoder.at
Similarly to [Decoder.at](https://circe.github.io/circe/api/io/circe/Decoder.html#at(field:String):io.circe.Decoder[A]) there should also exist a method `at` in `Encoder`

```scala
trait Encoder[A] extends Serializable { self =>
  (...)
  final def at(field: String): Encoder[A] = mapJson(j => Json.obj(field -> j))
}
```

### PR DESCRIPTION
**Pull request by Lasering**
Closes #1536

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, looks good to me, but do you mind adding a test [here](https://github.com/circe/circe/blob/master/modules/tests/shared/src/test/scala/io/circe/EncoderSuite.scala)?

**Comment by Lasering** [comment]
Added. Not sure if `m` should have a more complicated type.

**Comment by Lasering** [comment]
Class Codec no longer compiles because it inherits final member `at` from both `Encoder` and `Decoder`, and JVM does not have reification so we cannot overload a method with different return types.

How do you want to solve this problem? Rename Encoder.at to something else? Suggestions:

- `enclosed`
- `inside`
- `atField`
- `atObject`

**Comment by travisbrown** [comment]
Oh, right. Another alternative would be to add an `implicit x: Dummy` argument. Let's see if other people have preferences.

**Comment by Lasering** [comment]
:+1: on the dummy implicit.

**Comment by Lasering** [comment]
@travisbrown have you reached a decision on whether to use a different name or a dummy implicit? Meanwhile I changed my opinion. I think using a different, carefully chosen name is simpler and conveys the programmers objective better.

**Comment by Lasering** [comment]
@travisbrown implemented the DummyImplicit

**Comment by Lasering** [comment]
The approach of DummyImplicit fails if we want to implement an `at` for Codec (which would just return a `Codec.from(this.at(field), this.at(field))`)

**Pull request closed without merging**
